[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  external_node_modules = ["yt-dlp", "moviepy"]
  node_bundler = "esbuild"
